spring:
  application:
    name: order-service
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://localhost:5434/order_db
    username: order_ms
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      enabled: false

server:
  port: 8083

logging:
  level:
    org.springframework: DEBUG
