spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/order_db
    username: order_ms
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
